# -*- coding: utf-8 -*-
"""Análise_de_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWw2ycJoC1uDrfG4rL2zPfvV9uXz1cp2

# Tratamento de dados
"""

import pandas as pd #Manipulação e análise de dados
import seaborn as sns #Gráficos e visualizações estatísticas
import statistics as sts ##Calculos estatisticos (Ex. Mediana, média etc..)

dataset = pd.read_csv("Churn.csv", sep=";")
#Importa o csv e informa o tipo de separação das colunas

dataset.head()
#Mostra os cinco primeiros dados do dataset

dataset.columns = ["ID", "Score", "Estado", "Genero",
                   "Idade", "Patrimonio", "Saldo",
                   "Produtos", "TemCartaoCredito",
                   "Ativo", "Salario", "Saiu"]

dataset.head()

dataset.shape
#Mostra a quantidade de linhas e colunas

"""Análise de Dados - Dados textuais"""

agrupado = dataset.groupby(['Estado']).size()
#Agrupar e contar os dados

agrupado

agrupado.plot.bar()
#Gera um gráfico de barras

agrupado = dataset.groupby(['Genero']).size()
#Agrupar e contar os dados
agrupado

agrupado.plot.bar()

"""Análise de Variaveis Numéricas"""

dataset['Score'].describe()
#Calcular e mostrar vários
#Resultados estatísticos

sns.boxplot(dataset['Score'])
#Gerar um gráfico de dispersão

sns.distplot(dataset['Score'])
#Gera um gráfico de histograma

dataset['Idade'].describe()

sns.boxplot(dataset['Idade'])

sns.distplot(dataset['Idade'])

dataset['Salario'].describe()

sns.boxplot(dataset['Salario'])

sns.distplot(dataset['Salario'])

dataset['Saldo'].describe()

sns.boxplot(dataset['Saldo'])

sns.distplot(dataset['Saldo'])

"""Tratamento de dados"""

#Tratamento de dados ausentes/nulos
dataset.isnull().sum()
#Busca por dados nulos e soma

#Dados Textuais - Aplicar a MODA
dataset['Genero'].fillna('Masculino', inplace=True)
#Buscar pelos valores nulos
#E Substituir por um valor definido

dataset['Genero'].isnull().sum()

dataset.loc[dataset['Genero'] == 'M', 'Genero'] = 'Masculino'
#Localiza valores dentro do
#Dataset e Substituir por outro
#Valor definido

dataset.loc[dataset['Genero'].isin(['Fem', 'F']), 'Genero'] = "Feminino"

agrupado = dataset.groupby(['Genero']).size()
#Agrupar e contar os dados
agrupado

mediana = sts.median(dataset['Idade'])
#Calcular a mediana de idade
mediana

dataset.loc[(dataset['Idade'] < 0) | (dataset['Idade'] > 116)]
#Localiza idades menores que zero e maiores que 116

dataset.loc[(dataset['Idade'] < 0) | (dataset['Idade'] > 116), 'Idade'] = mediana

dataset.loc[(dataset['Idade'] < 0) | (dataset['Idade'] > 116)]

dataset[dataset.duplicated(['ID'], keep=False)]
#Pesquisa por valores duplicados

dataset.drop_duplicates(subset='ID', keep='first', inplace=True)
#Exclui os valores duplicados do parâmetro

dataset[dataset.duplicated(['ID'], keep=False)]

dataset.loc[dataset['Estado'].isin(['RP', 'SP', 'TD']), 'Estado'] = "RS"

agrupado = dataset.groupby(['Estado']).size()
agrupado

mediana = sts.median(dataset['Salario'])
mediana

dataset['Salario'].fillna(mediana, inplace=True)
#Substituir os valores nulos pela mediana

desvio = sts.stdev(dataset['Salario'])
desvio

dataset.loc[dataset['Salario'] > 2 * desvio, 'Salario'] = mediana

dataset.loc[dataset['Salario'] > 2 * desvio]