# -*- coding: utf-8 -*-
"""Iris (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqIhlQpaIlo84Hg4JJlxpqSoMny-E7DM
"""

#Sklearn - https://scikit-learn.org/stable/
#Divide os dados em dados de treino e dados de teste
from sklearn.model_selection import train_test_split
#Avaliação do modelo com precisão e matrix de confusãi
from sklearn.metrics import accuracy_score, confusion_matrix
#Algoritmo de KNN - Classificação por vizinhos (aproximação)
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
#Estatisticas
from scipy import stats

dataset.head()

dataset = pd.read_csv('iris.csv', sep=',')

dataset.head()

dataset.shape

#Converter os dados em um dataframe
dados = pd.DataFrame(dataset)

#Analisar as estatisticas dos dados
dados.describe()

#Conta a quantidade de dados por classe
dados['class'].value_counts()

#Seleciona as 4 pirmeiras colunas e
#salva na variavel previsores
previsores = dados.iloc[:,0:4].values
#Seleciona a ultima coluna e salva
#na variavel classe
classe = dados.iloc[:,4].values

#70/30
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(
    previsores,
    classe,
    test_size = 0.3,
    random_state = 0
)
#Separação dos dados em 70% para treinamento e 30% para teste

#Calcula o tamanho dos dados de treinamento
len(X_treinamento)

#Escolhe o algoritmo de KNN
#E a quantidade de vizinhos (3)
knn = KNeighborsClassifier(n_neighbors = 3)

#Função para treinar o modelo com os dados
knn.fit(X_treinamento, y_treinamento)

#Função para prever/testar o modelo
prova = knn.predict(X_teste)

prova

#Calcula a quantidade x acertos
acertos = accuracy_score(y_teste,prova)
acertos

#Matriz de confusão
confusao = confusion_matrix(y_teste, prova)
confusao