# -*- coding: utf-8 -*-
"""Regressão_Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TM-GLHbz85wzrqHH4asx9cQOx_8-bj19
"""

import pandas as pd #Manipulação de dados
import numpy as np #Calculos e estatísticas
import matplotlib.pyplot as plt #Gráficos

from sklearn.linear_model import LinearRegression
#Modelo de Regressão Linear
from yellowbrick.regressor import ResidualsPlot
#Visualizar os residuos

base = pd.read_csv('cars.csv')
base.head()

base.shape

base = base.drop(['Unnamed: 0'], axis=1)
#Remover uma coluna que não precisamos
base.head()

X = base.iloc[:,1].values
#Dados da distância
Y = base.iloc[:,0].values
#Dados da velocidade

X

Y

"""Correlação"""

correlacao = np.corrcoef(X,Y)
#Executa o cálculo de correlação

correlacao

X = X.reshape(-1,1)
#Converte X em uma matriz unidimensional
#Requisito para usar a biblioteca do Sklearn

modelo = LinearRegression()
#Cria o modelo de regressão linear com
#Todas as regras e fórmulas

modelo.fit(X,Y)
#Treinamento do modelo com os dados

"""Intersecção"""

modelo.intercept_
#Calcula a intersecção

"""Inclinação"""

modelo.coef_
#Calcula a inclinação da reta

plt.scatter(X,Y) #Pontos no plano do gráfico
plt.plot(X, modelo.predict(X))
#Linha da regressão
plt.xlabel('Distância') #Texto de X
plt.ylabel('Velocidade') #Texto de Y
plt.show() #Mostra o gráfico

modelo.intercept_ + (modelo.coef_ * 3)
#Previsão para descobrir a velocidade
#Da distância do valor 3

modelo.predict([[3]])
#Função para previsão (fórmula anterior)

"""Residuos"""

visualizador = ResidualsPlot(modelo)
#Visualiza os residuos
visualizador.fit(X,Y)
visualizador.poof()