# -*- coding: utf-8 -*-
"""Regras_de_associação (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaMW30Y6iTRKxUGOmJYfxpOzX9u-ZlI_
"""

import pandas as pd
!pip install apyori #Instalar a biblioteca
from apyori import apriori

dados = pd.read_csv('transacoes.txt', header = None)
dados
#Importa o txt e diz que não tem cabeçalho

dados.shape

transacoes = []
for i in range(0,6):
  transacoes.append([str(dados.values[i,j]) for j in range(0,3)])
transacoes

#Regras de apriori
regras = apriori(
    transacoes,
    min_support = 0.5, #Suporte mínimo de 50%
    min_confidence = 0.5, #Confiança mínima de 50%
    min_length = 2 #Relação de pelo menos 2 itens
)

resultados = list(regras)
#Converte o resultado em uma lista

print(resultados[0])

resultados

#Converter o resultado em lista pra ficar mais visivel
resultados2 = [list(x) for x in resultados]
resultados2

#Finalizando a lista organizada
resultados3 = []
for j in range (0,7):
  resultados3.append([list(x) for x in resultados2[j][2]])
resultados3

itens = {'Pizza', 'Sorvete'}

#Consultando os resultados
for resultado in resultados:
  itens_regra = set(resultado.items)
  if itens.issubset(itens_regra):
    print("Suporte: ", resultado.support)
    for estatistica in resultado.ordered_statistics:
      print("itens: ", set(estatistica.items_base), "-->", set(estatistica.items_add))
      print("confianca: ", estatistica.confidence)
      print("lift: ", estatistica.lift)