# -*- coding: utf-8 -*-
"""Árvore_de_decisão e Rede bayesiana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNUe3s58QvlgMGsmyibvih9QmFAyvQIG
"""

import pandas as pd
from sklearn.model_selection import train_test_split #treino e teste
from sklearn.metrics import accuracy_score, confusion_matrix #precisão e matrix e confusão

from sklearn.tree import DecisionTreeClassifier #Modelo de árvore de decisão
from sklearn.preprocessing import LabelEncoder #pré-processamento dos dados
import matplotlib.pyplot as plt #graficos
import seaborn as sns
#Exportações e visualizações da árvore
import graphlib
import graphviz
from sklearn.tree import export_graphviz

credito = pd.read_csv('Credit.csv')
credito.head()

credito.shape

#Separar os parâmetros e a classe
previsores = credito.iloc[:,0:20].values
classe = credito.iloc[:,20].values

labelencoder1 = LabelEncoder()
previsores[:,0] = labelencoder1.fit_transform(previsores[:,0])

labelencoder2 = LabelEncoder()
previsores[:,2] = labelencoder2.fit_transform(previsores[:,2])

labelencoder3 = LabelEncoder()
previsores[:,3] = labelencoder3.fit_transform(previsores[:,3])

labelencoder5 = LabelEncoder()
previsores[:,5] = labelencoder5.fit_transform(previsores[:,5])

labelencoder6 = LabelEncoder()
previsores[:,6] = labelencoder6.fit_transform(previsores[:,6])

labelencoder8 = LabelEncoder()
previsores[:,8] = labelencoder8.fit_transform(previsores[:,8])

labelencoder9 = LabelEncoder()
previsores[:,9] = labelencoder9.fit_transform(previsores[:,9])

labelencoder11 = LabelEncoder()
previsores[:,11] = labelencoder11.fit_transform(previsores[:,11])

labelencoder13 = LabelEncoder()
previsores[:,13] = labelencoder13.fit_transform(previsores[:,13])

labelencoder14 = LabelEncoder()
previsores[:,14] = labelencoder14.fit_transform(previsores[:,14])

labelencoder16 = LabelEncoder()
previsores[:,16] = labelencoder16.fit_transform(previsores[:,16])

labelencoder18 = LabelEncoder()
previsores[:,18] = labelencoder18.fit_transform(previsores[:,18])

labelencoder19 = LabelEncoder()
previsores[:,19] = labelencoder19.fit_transform(previsores[:,19])

#Separar os dados em treinamento e teste
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

arvore = DecisionTreeClassifier() #Criar o modelo de árvore de decisão

arvore.fit(X_treinamento, y_treinamento) #treina o modelo com os dados

previsoes = arvore.predict(X_teste) #faz o teste com os dados separados

previsoes

taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

confusao = confusion_matrix(y_teste, previsoes)
confusao

exportar = export_graphviz(
    arvore, out_file=None, filled=True,
    feature_names=credito.columns[0:20],
    class_names=['Mau pagador','Bom Pagador'],
    special_characters=True
)

graph = graphviz.Source(exportar)
graph.render("Arvore_de_decisao")
graph.view()

# matrix = ConfunsionMatrix(GaussianNB())
# matrix.fit(X_treinamento, y_treinamento)
# previsoes = matrix.predict(X_teste, y_teste)
# matrix.poof()

plt.figure(figsize=(8,6))
sns.heatmap(confusao, annot=True, cmap="Greens", cbar=False, fmt="d",
xticklabels=['Mau pagador', 'Bom pagador'], yticklabels=['Mau pagador', 'Bom pagador'])
plt.title("Matriz de confusão")
plt.xlabel("Previsão")
plt.ylabel("Real")
plt.show()

"""Rede Bayesiana"""

from sklearn.naive_bayes import GaussianNB

naive_bayes = GaussianNB()

naive_bayes.fit(X_treinamento, y_treinamento)
#treina os mesmos dados porém com algoritmo de rede bayesiana

previsoes2 = naive_bayes.predict(X_teste)

previsoes2

taxa_acerto = accuracy_score(y_teste, previsoes2)
taxa_acerto

confusao = confusion_matrix(y_teste, previsoes2)
confusao

"""Rede Bayesiana"""

#Reaproveitamos as mesmas bibliotecas da
#árvore de decisão
from sklearn.naive_bayes import GaussianNB
#Bibliote de rede bayesiana

naive_bayes = GaussianNB()
#Importa as regras da rede bayesiana

naive_bayes.fit(X_treinamento, y_treinamento)
#treina os mesmos dados porém com algoritmo de rede bayesiana

previsoes2 = naive_bayes.predict(X_teste)
#Aplica a prova para a IA de rede bayesiana

previsoes2

taxa_acerto = accuracy_score(y_teste, previsoes2)
taxa_acerto
#Calcula o valor do aprendizado

plt.figure(figsize=(8,6))
sns.heatmap(confusao, annot=True, cmap="Greens", cbar=False, fmt="d",
xticklabels=['Mau pagador', 'Bom pagador'], yticklabels=['Mau pagador', 'Bom pagador'])
plt.title('Matriz de confusão')
plt.xlabel('Previsão')
plt.ylabel('Real')
plt.show()